### ISSUE TITLE
potatso http_simple该如何填写呢？

### ISSUE THREAD

**Issue by ygfly** [icodesign/Potatso-ssr_obfs#1]
m.masl.abcd.com.cn
AppType: Android
Accept: application/json
混淆代码是3行，potatso只能填一行，该怎样填呢？
m.masl.abcd.com.cn#AppType: Android\nAccept: application/json   没有混淆效果
m.masl.abcd.com.cn\nAppType: Android\nAccept: application/json   无法连接

**Comment by icodesign** [comment]
试试 `m.masl.abcd.com.cn\r\nAppType: Android\r\nAccept: application/json`

**Comment by icodesign** [comment]
已在 Telegram 中回复：`m.masl.abcd.com.cn#AppType: Android\nAccept: application/json` 是正确的写法，如果确认没有混淆效果，可以把抓包内容发上来看看
